# Generated by Django 5.1.7 on 2025-06-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tornei', '0001_initial'),
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partecipatorneo',
            name='sportivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utenti.sportivo'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='gestore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tornei', to='tornei.gestoretorneo'),
        ),
        migrations.AddField(
            model_name='partecipatorneo',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tornei.torneo'),
        ),
    ]
