# Generated by Django 5.1.7 on 2025-06-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttivitaSportiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('orario', models.TimeField()),
                ('giorno_settimana', models.CharField(max_length=15)),
                ('max_partecipanti', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PartecipaAttivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
