# Generated by Django 5.1.7 on 2025-06-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attivitasportiva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_recensione', models.DateField()),
                ('attivita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attivitasportiva.attivitasportiva')),
            ],
        ),
    ]
