# Generated by Django 5.1.7 on 2025-06-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recensioni', '0001_initial'),
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensione',
            name='sportivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utenti.sportivo'),
        ),
    ]
